name: Build KeyFlare executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # latest python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script on Linux and macOS
        if: matrix.os != 'windows-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole keyflare/main.py

      - name: Run build script on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole --windowed keyflare/main.py
